#!/usr/bin/env python3
from boiler.cli import cli as kernel

# root project command
cli = kernel.cli

# add orm cli
# from boiler.cli import db
# cli.add_command(db.cli, name='db')


# and run
cli()

